// Code generated by protoc-gen-go. DO NOT EDIT.
// source: balance.proto

package balance

import proto "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"

import (
	context "golang.org/x/net/context"
	grpc "google.golang.org/grpc"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion2 // please upgrade the proto package

type BalanceRequest struct {
	Did                  string   `protobuf:"bytes,1,opt,name=did,proto3" json:"did,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *BalanceRequest) Reset()         { *m = BalanceRequest{} }
func (m *BalanceRequest) String() string { return proto.CompactTextString(m) }
func (*BalanceRequest) ProtoMessage()    {}
func (*BalanceRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_balance_60f00aee5f5346bb, []int{0}
}
func (m *BalanceRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_BalanceRequest.Unmarshal(m, b)
}
func (m *BalanceRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_BalanceRequest.Marshal(b, m, deterministic)
}
func (dst *BalanceRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_BalanceRequest.Merge(dst, src)
}
func (m *BalanceRequest) XXX_Size() int {
	return xxx_messageInfo_BalanceRequest.Size(m)
}
func (m *BalanceRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_BalanceRequest.DiscardUnknown(m)
}

var xxx_messageInfo_BalanceRequest proto.InternalMessageInfo

func (m *BalanceRequest) GetDid() string {
	if m != nil {
		return m.Did
	}
	return ""
}

type BalanceResponse struct {
	Balance              int32     `protobuf:"varint,1,opt,name=balance,proto3" json:"balance,omitempty"`
	Actions              []*Action `protobuf:"bytes,2,rep,name=actions,proto3" json:"actions,omitempty"`
	XXX_NoUnkeyedLiteral struct{}  `json:"-"`
	XXX_unrecognized     []byte    `json:"-"`
	XXX_sizecache        int32     `json:"-"`
}

func (m *BalanceResponse) Reset()         { *m = BalanceResponse{} }
func (m *BalanceResponse) String() string { return proto.CompactTextString(m) }
func (*BalanceResponse) ProtoMessage()    {}
func (*BalanceResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_balance_60f00aee5f5346bb, []int{1}
}
func (m *BalanceResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_BalanceResponse.Unmarshal(m, b)
}
func (m *BalanceResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_BalanceResponse.Marshal(b, m, deterministic)
}
func (dst *BalanceResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_BalanceResponse.Merge(dst, src)
}
func (m *BalanceResponse) XXX_Size() int {
	return xxx_messageInfo_BalanceResponse.Size(m)
}
func (m *BalanceResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_BalanceResponse.DiscardUnknown(m)
}

var xxx_messageInfo_BalanceResponse proto.InternalMessageInfo

func (m *BalanceResponse) GetBalance() int32 {
	if m != nil {
		return m.Balance
	}
	return 0
}

func (m *BalanceResponse) GetActions() []*Action {
	if m != nil {
		return m.Actions
	}
	return nil
}

type BalanceUpdate struct {
	Did                  string    `protobuf:"bytes,1,opt,name=did,proto3" json:"did,omitempty"`
	Actions              []*Action `protobuf:"bytes,2,rep,name=actions,proto3" json:"actions,omitempty"`
	UpdatedBy            string    `protobuf:"bytes,3,opt,name=updatedBy,proto3" json:"updatedBy,omitempty"`
	XXX_NoUnkeyedLiteral struct{}  `json:"-"`
	XXX_unrecognized     []byte    `json:"-"`
	XXX_sizecache        int32     `json:"-"`
}

func (m *BalanceUpdate) Reset()         { *m = BalanceUpdate{} }
func (m *BalanceUpdate) String() string { return proto.CompactTextString(m) }
func (*BalanceUpdate) ProtoMessage()    {}
func (*BalanceUpdate) Descriptor() ([]byte, []int) {
	return fileDescriptor_balance_60f00aee5f5346bb, []int{2}
}
func (m *BalanceUpdate) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_BalanceUpdate.Unmarshal(m, b)
}
func (m *BalanceUpdate) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_BalanceUpdate.Marshal(b, m, deterministic)
}
func (dst *BalanceUpdate) XXX_Merge(src proto.Message) {
	xxx_messageInfo_BalanceUpdate.Merge(dst, src)
}
func (m *BalanceUpdate) XXX_Size() int {
	return xxx_messageInfo_BalanceUpdate.Size(m)
}
func (m *BalanceUpdate) XXX_DiscardUnknown() {
	xxx_messageInfo_BalanceUpdate.DiscardUnknown(m)
}

var xxx_messageInfo_BalanceUpdate proto.InternalMessageInfo

func (m *BalanceUpdate) GetDid() string {
	if m != nil {
		return m.Did
	}
	return ""
}

func (m *BalanceUpdate) GetActions() []*Action {
	if m != nil {
		return m.Actions
	}
	return nil
}

func (m *BalanceUpdate) GetUpdatedBy() string {
	if m != nil {
		return m.UpdatedBy
	}
	return ""
}

type BalanceUpdateResponse struct {
	Message              string         `protobuf:"bytes,1,opt,name=message,proto3" json:"message,omitempty"`
	Update               *BalanceUpdate `protobuf:"bytes,2,opt,name=update,proto3" json:"update,omitempty"`
	XXX_NoUnkeyedLiteral struct{}       `json:"-"`
	XXX_unrecognized     []byte         `json:"-"`
	XXX_sizecache        int32          `json:"-"`
}

func (m *BalanceUpdateResponse) Reset()         { *m = BalanceUpdateResponse{} }
func (m *BalanceUpdateResponse) String() string { return proto.CompactTextString(m) }
func (*BalanceUpdateResponse) ProtoMessage()    {}
func (*BalanceUpdateResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_balance_60f00aee5f5346bb, []int{3}
}
func (m *BalanceUpdateResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_BalanceUpdateResponse.Unmarshal(m, b)
}
func (m *BalanceUpdateResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_BalanceUpdateResponse.Marshal(b, m, deterministic)
}
func (dst *BalanceUpdateResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_BalanceUpdateResponse.Merge(dst, src)
}
func (m *BalanceUpdateResponse) XXX_Size() int {
	return xxx_messageInfo_BalanceUpdateResponse.Size(m)
}
func (m *BalanceUpdateResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_BalanceUpdateResponse.DiscardUnknown(m)
}

var xxx_messageInfo_BalanceUpdateResponse proto.InternalMessageInfo

func (m *BalanceUpdateResponse) GetMessage() string {
	if m != nil {
		return m.Message
	}
	return ""
}

func (m *BalanceUpdateResponse) GetUpdate() *BalanceUpdate {
	if m != nil {
		return m.Update
	}
	return nil
}

type SubscribeRequest struct {
	SubscriberId         string   `protobuf:"bytes,1,opt,name=subscriberId,proto3" json:"subscriberId,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *SubscribeRequest) Reset()         { *m = SubscribeRequest{} }
func (m *SubscribeRequest) String() string { return proto.CompactTextString(m) }
func (*SubscribeRequest) ProtoMessage()    {}
func (*SubscribeRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_balance_60f00aee5f5346bb, []int{4}
}
func (m *SubscribeRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_SubscribeRequest.Unmarshal(m, b)
}
func (m *SubscribeRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_SubscribeRequest.Marshal(b, m, deterministic)
}
func (dst *SubscribeRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_SubscribeRequest.Merge(dst, src)
}
func (m *SubscribeRequest) XXX_Size() int {
	return xxx_messageInfo_SubscribeRequest.Size(m)
}
func (m *SubscribeRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_SubscribeRequest.DiscardUnknown(m)
}

var xxx_messageInfo_SubscribeRequest proto.InternalMessageInfo

func (m *SubscribeRequest) GetSubscriberId() string {
	if m != nil {
		return m.SubscriberId
	}
	return ""
}

type Action struct {
	Id                   string   `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Timestamp            string   `protobuf:"bytes,2,opt,name=timestamp,proto3" json:"timestamp,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Action) Reset()         { *m = Action{} }
func (m *Action) String() string { return proto.CompactTextString(m) }
func (*Action) ProtoMessage()    {}
func (*Action) Descriptor() ([]byte, []int) {
	return fileDescriptor_balance_60f00aee5f5346bb, []int{5}
}
func (m *Action) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Action.Unmarshal(m, b)
}
func (m *Action) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Action.Marshal(b, m, deterministic)
}
func (dst *Action) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Action.Merge(dst, src)
}
func (m *Action) XXX_Size() int {
	return xxx_messageInfo_Action.Size(m)
}
func (m *Action) XXX_DiscardUnknown() {
	xxx_messageInfo_Action.DiscardUnknown(m)
}

var xxx_messageInfo_Action proto.InternalMessageInfo

func (m *Action) GetId() string {
	if m != nil {
		return m.Id
	}
	return ""
}

func (m *Action) GetTimestamp() string {
	if m != nil {
		return m.Timestamp
	}
	return ""
}

func init() {
	proto.RegisterType((*BalanceRequest)(nil), "BalanceRequest")
	proto.RegisterType((*BalanceResponse)(nil), "BalanceResponse")
	proto.RegisterType((*BalanceUpdate)(nil), "BalanceUpdate")
	proto.RegisterType((*BalanceUpdateResponse)(nil), "BalanceUpdateResponse")
	proto.RegisterType((*SubscribeRequest)(nil), "SubscribeRequest")
	proto.RegisterType((*Action)(nil), "Action")
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion4

// BalanceClient is the client API for Balance service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type BalanceClient interface {
	GetBalance(ctx context.Context, in *BalanceRequest, opts ...grpc.CallOption) (*BalanceResponse, error)
	UpdateBalance(ctx context.Context, in *BalanceUpdate, opts ...grpc.CallOption) (*BalanceUpdateResponse, error)
	UpdateBalanceSubscribe(ctx context.Context, in *SubscribeRequest, opts ...grpc.CallOption) (Balance_UpdateBalanceSubscribeClient, error)
}

type balanceClient struct {
	cc *grpc.ClientConn
}

func NewBalanceClient(cc *grpc.ClientConn) BalanceClient {
	return &balanceClient{cc}
}

func (c *balanceClient) GetBalance(ctx context.Context, in *BalanceRequest, opts ...grpc.CallOption) (*BalanceResponse, error) {
	out := new(BalanceResponse)
	err := c.cc.Invoke(ctx, "/balance/GetBalance", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *balanceClient) UpdateBalance(ctx context.Context, in *BalanceUpdate, opts ...grpc.CallOption) (*BalanceUpdateResponse, error) {
	out := new(BalanceUpdateResponse)
	err := c.cc.Invoke(ctx, "/balance/UpdateBalance", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *balanceClient) UpdateBalanceSubscribe(ctx context.Context, in *SubscribeRequest, opts ...grpc.CallOption) (Balance_UpdateBalanceSubscribeClient, error) {
	stream, err := c.cc.NewStream(ctx, &_Balance_serviceDesc.Streams[0], "/balance/UpdateBalanceSubscribe", opts...)
	if err != nil {
		return nil, err
	}
	x := &balanceUpdateBalanceSubscribeClient{stream}
	if err := x.ClientStream.SendMsg(in); err != nil {
		return nil, err
	}
	if err := x.ClientStream.CloseSend(); err != nil {
		return nil, err
	}
	return x, nil
}

type Balance_UpdateBalanceSubscribeClient interface {
	Recv() (*BalanceUpdateResponse, error)
	grpc.ClientStream
}

type balanceUpdateBalanceSubscribeClient struct {
	grpc.ClientStream
}

func (x *balanceUpdateBalanceSubscribeClient) Recv() (*BalanceUpdateResponse, error) {
	m := new(BalanceUpdateResponse)
	if err := x.ClientStream.RecvMsg(m); err != nil {
		return nil, err
	}
	return m, nil
}

// BalanceServer is the server API for Balance service.
type BalanceServer interface {
	GetBalance(context.Context, *BalanceRequest) (*BalanceResponse, error)
	UpdateBalance(context.Context, *BalanceUpdate) (*BalanceUpdateResponse, error)
	UpdateBalanceSubscribe(*SubscribeRequest, Balance_UpdateBalanceSubscribeServer) error
}

func RegisterBalanceServer(s *grpc.Server, srv BalanceServer) {
	s.RegisterService(&_Balance_serviceDesc, srv)
}

func _Balance_GetBalance_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(BalanceRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(BalanceServer).GetBalance(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/balance/GetBalance",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(BalanceServer).GetBalance(ctx, req.(*BalanceRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Balance_UpdateBalance_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(BalanceUpdate)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(BalanceServer).UpdateBalance(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/balance/UpdateBalance",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(BalanceServer).UpdateBalance(ctx, req.(*BalanceUpdate))
	}
	return interceptor(ctx, in, info, handler)
}

func _Balance_UpdateBalanceSubscribe_Handler(srv interface{}, stream grpc.ServerStream) error {
	m := new(SubscribeRequest)
	if err := stream.RecvMsg(m); err != nil {
		return err
	}
	return srv.(BalanceServer).UpdateBalanceSubscribe(m, &balanceUpdateBalanceSubscribeServer{stream})
}

type Balance_UpdateBalanceSubscribeServer interface {
	Send(*BalanceUpdateResponse) error
	grpc.ServerStream
}

type balanceUpdateBalanceSubscribeServer struct {
	grpc.ServerStream
}

func (x *balanceUpdateBalanceSubscribeServer) Send(m *BalanceUpdateResponse) error {
	return x.ServerStream.SendMsg(m)
}

var _Balance_serviceDesc = grpc.ServiceDesc{
	ServiceName: "balance",
	HandlerType: (*BalanceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "GetBalance",
			Handler:    _Balance_GetBalance_Handler,
		},
		{
			MethodName: "UpdateBalance",
			Handler:    _Balance_UpdateBalance_Handler,
		},
	},
	Streams: []grpc.StreamDesc{
		{
			StreamName:    "UpdateBalanceSubscribe",
			Handler:       _Balance_UpdateBalanceSubscribe_Handler,
			ServerStreams: true,
		},
	},
	Metadata: "balance.proto",
}

func init() { proto.RegisterFile("balance.proto", fileDescriptor_balance_60f00aee5f5346bb) }

var fileDescriptor_balance_60f00aee5f5346bb = []byte{
	// 303 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x8c, 0x52, 0x4d, 0x4f, 0x84, 0x30,
	0x10, 0x0d, 0x6c, 0x84, 0x30, 0x2b, 0x2c, 0x36, 0x71, 0x43, 0x36, 0x1e, 0xb0, 0x07, 0xc3, 0xa9,
	0x1a, 0x4c, 0xd6, 0xb3, 0x9b, 0x18, 0xe3, 0xc5, 0x03, 0xc6, 0x83, 0xc7, 0x02, 0x8d, 0x21, 0x91,
	0x0f, 0x69, 0x39, 0xf8, 0xd7, 0xfc, 0x75, 0x66, 0x0b, 0xed, 0x5a, 0xd4, 0xc4, 0x1b, 0xf3, 0x98,
	0xf7, 0xde, 0xbc, 0x99, 0x82, 0x9f, 0xd3, 0x37, 0xda, 0x14, 0x8c, 0x74, 0x7d, 0x2b, 0x5a, 0x8c,
	0x21, 0xd8, 0x8d, 0x40, 0xc6, 0xde, 0x07, 0xc6, 0x05, 0x0a, 0x61, 0x51, 0x56, 0x65, 0x64, 0xc5,
	0x56, 0xe2, 0x65, 0xfb, 0x4f, 0xfc, 0x08, 0x2b, 0xdd, 0xc3, 0xbb, 0xb6, 0xe1, 0x0c, 0x45, 0xe0,
	0x4e, 0x3a, 0xb2, 0xf1, 0x28, 0x53, 0x25, 0x3a, 0x07, 0x97, 0x16, 0xa2, 0x6a, 0x1b, 0x1e, 0xd9,
	0xf1, 0x22, 0x59, 0xa6, 0x2e, 0xb9, 0x95, 0x75, 0xa6, 0x70, 0x9c, 0x83, 0x3f, 0xe9, 0x3d, 0x77,
	0x25, 0x15, 0xec, 0xa7, 0xe5, 0x3f, 0x54, 0xd0, 0x19, 0x78, 0x83, 0xa4, 0x97, 0xbb, 0x8f, 0x68,
	0x21, 0xa9, 0x07, 0x00, 0xbf, 0xc0, 0xa9, 0xe1, 0xf1, 0x7d, 0xf2, 0x9a, 0x71, 0x4e, 0x5f, 0xd9,
	0xe4, 0xa7, 0x4a, 0x74, 0x01, 0xce, 0xc8, 0x8f, 0xec, 0xd8, 0x4a, 0x96, 0x69, 0x40, 0x4c, 0x85,
	0xe9, 0x2f, 0xde, 0x42, 0xf8, 0x34, 0xe4, 0xbc, 0xe8, 0xab, 0x5c, 0x2f, 0x0d, 0xc3, 0x31, 0x57,
	0x58, 0xff, 0xa0, 0xa2, 0x18, 0x18, 0xde, 0x82, 0x33, 0x66, 0x40, 0x01, 0xd8, 0x3a, 0xae, 0x5d,
	0x95, 0xfb, 0x28, 0xa2, 0xaa, 0x19, 0x17, 0xb4, 0xee, 0xa4, 0xb9, 0x97, 0x1d, 0x80, 0xf4, 0xd3,
	0xd2, 0xcb, 0x46, 0x97, 0x00, 0xf7, 0x4c, 0x4c, 0x73, 0xa1, 0x15, 0x31, 0x6f, 0xb7, 0x09, 0xc9,
	0xfc, 0x50, 0x37, 0xe0, 0x8f, 0xe3, 0x2b, 0xce, 0x2c, 0xd5, 0x66, 0x4d, 0x7e, 0xdf, 0xd3, 0x1d,
	0xac, 0x0d, 0xa2, 0x8e, 0x8c, 0x4e, 0xc8, 0x3c, 0xfe, 0x5f, 0x22, 0x57, 0x56, 0xee, 0xc8, 0x67,
	0x76, 0xfd, 0x15, 0x00, 0x00, 0xff, 0xff, 0xad, 0xc0, 0x9c, 0x5b, 0x77, 0x02, 0x00, 0x00,
}
